apiVersion: eventing.fluss.io/v1alpha1
kind: Broker
metadata:
  name: default
  namespace: default
spec:
  config:
    fluss:
      cluster:
        endpoint: "fluss://fluss-cluster:9123"
    ingress:
      replicas: 1
    schema:
      enabled: true
      auto-register: true
    iceberg:
      enabled: false
